export interface Tool {
  id: string;
  name: string;
  category: string;
  description: string;
  icon: string;
  route: string;
  isBookmarked?: boolean;
  usageCount?: number;
  lastUsed?: string;
  color: string;
}

export const toolCategories = [
  { id: 'all', name: 'All Tools', icon: 'fas fa-th-large' },
  { id: 'office', name: 'MS Office Suite', icon: 'fas fa-microsoft' },
  { id: 'media', name: 'Media Tools', icon: 'fas fa-photo-video' },
  { id: 'developer', name: 'Developer Tools', icon: 'fas fa-code' },
  { id: 'content', name: 'Content Creation', icon: 'fas fa-pen-fancy' },
  { id: 'text', name: 'Text Analysis', icon: 'fas fa-font' },
  { id: 'financial', name: 'Financial Tools', icon: 'fas fa-chart-line' },
  { id: 'productivity', name: 'Productivity', icon: 'fas fa-tasks' },
  { id: 'utilities', name: 'Utilities', icon: 'fas fa-tools' },
  { id: 'converters', name: 'Converters', icon: 'fas fa-exchange-alt' },
  { id: 'security', name: 'Security Tools', icon: 'fas fa-shield-halved' },
  { id: 'generators', name: 'Generators', icon: 'fas fa-magic-wand-sparkles' },
  { id: 'calculators', name: 'Calculators', icon: 'fas fa-calculator' },
  { id: 'networking', name: 'Network Tools', icon: 'fas fa-network-wired' },
  { id: 'ai', name: 'AI & Automation', icon: 'fas fa-robot' },
];

export const tools: Tool[] = [
  // MS Office Suite
  {
    id: 'word-processor',
    name: 'Word Processor',
    category: 'office',
    description: 'Create and edit documents with rich text formatting, tables, and images',
    icon: 'fas fa-file-word',
    route: '/tools/word-processor',
    color: 'blue',
  },
  {
    id: 'spreadsheet',
    name: 'Spreadsheet',
    category: 'office',
    description: 'Create spreadsheets with formulas, charts, and data analysis tools',
    icon: 'fas fa-file-excel',
    route: '/tools/spreadsheet',
    color: 'green',
  },
  {
    id: 'presentation',
    name: 'Presentation',
    category: 'office',
    description: 'Create professional presentations with slides, animations, and multimedia',
    icon: 'fas fa-file-powerpoint',
    route: '/tools/presentation',
    color: 'orange',
  },
  {
    id: 'email-client',
    name: 'Email Client',
    category: 'office',
    description: 'Manage emails, calendar, contacts, and tasks in one place',
    icon: 'fas fa-envelope',
    route: '/tools/email-client',
    color: 'blue',
  },
  {
    id: 'database-manager',
    name: 'Database Manager',
    category: 'office',
    description: 'Create and manage databases with forms, queries, and reports',
    icon: 'fas fa-database',
    route: '/tools/database-manager',
    color: 'red',
  },
  {
    id: 'note-taking',
    name: 'Advanced Notes',
    category: 'office',
    description: 'Organize notes with sections, pages, and multimedia content',
    icon: 'fas fa-sticky-note',
    route: '/tools/note-taking',
    color: 'purple',
  },

  // Media Tools
  {
    id: 'image-resizer',
    name: 'Image Resizer',
    category: 'media',
    description: 'Resize and optimize images for web, social media, and print',
    icon: 'fas fa-expand-arrows-alt',
    route: '/tools/image-resizer',
    color: 'blue',
  },
  {
    id: 'file-share',
    name: 'File Share Tool',
    category: 'utilities',
    description: 'Upload files aur QR code ke saath share karo. Files save ho jaati hain aur download tracking hoti hai',
    icon: 'fas fa-share-alt',
    route: '/tools/file-share',
    color: 'purple',
  },
  {
    id: 'pdf-merger',
    name: 'PDF Merger',
    category: 'media',
    description: 'Combine multiple PDF files into a single document',
    icon: 'fas fa-file-pdf',
    route: '/tools/pdf-merger',
    color: 'red',
  },
  {
    id: 'video-to-gif',
    name: 'Video to GIF',
    category: 'media',
    description: 'Convert video clips to animated GIF files',
    icon: 'fas fa-video',
    route: '/tools/video-to-gif',
    color: 'green',
  },
  {
    id: 'image-optimizer',
    name: 'Image Optimizer',
    category: 'media',
    description: 'Compress and optimize images without quality loss',
    icon: 'fas fa-image',
    route: '/tools/image-optimizer',
    color: 'purple',
  },
  {
    id: 'audio-converter',
    name: 'Audio Converter',
    category: 'media',
    description: 'Convert audio files between different formats',
    icon: 'fas fa-music',
    route: '/tools/audio-converter',
    color: 'pink',
  },
  {
    id: 'ocr-text-extractor',
    name: 'OCR Text Extractor',
    category: 'media',
    description: 'Extract text from images using OCR technology',
    icon: 'fas fa-text-width',
    route: '/tools/ocr-text-extractor',
    color: 'indigo',
  },
  {
    id: 'video-editor',
    name: 'Video Editor',
    category: 'media',
    description: 'Professional video editing with trimming, merging, and subtitle features',
    icon: 'fas fa-video-camera',
    route: '/tools/video-editor',
    color: 'red',
  },
  {
    id: 'audio-editor',
    name: 'Audio Editor',
    category: 'media',
    description: 'Edit audio with trimming, mixing, and noise reduction tools',
    icon: 'fas fa-waveform',
    route: '/tools/audio-editor',
    color: 'green',
  },
  {
    id: 'image-editor',
    name: 'Image Editor',
    category: 'media',
    description: 'Advanced image editing with filters, adjustments, and effects',
    icon: 'fas fa-edit',
    route: '/tools/image-editor',
    color: 'blue',
  },
  {
    id: 'gif-maker',
    name: 'GIF Maker',
    category: 'media',
    description: 'Create animated GIFs from multiple images with customizable settings',
    icon: 'fas fa-images',
    route: '/tools/gif-maker',
    color: 'orange',
  },
  {
    id: 'watermark-tool',
    name: 'Watermark Tool',
    category: 'media',
    description: 'Add text or image watermarks to your images and videos',
    icon: 'fas fa-stamp',
    route: '/tools/watermark-tool',
    color: 'purple',
  },
  
  // Developer Tools
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    category: 'developer',
    description: 'Format, validate and beautify JSON data',
    icon: 'fab fa-js-square',
    route: '/tools/json-formatter',
    color: 'yellow',
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    category: 'developer',
    description: 'Test and debug regular expressions with live matching',
    icon: 'fas fa-search',
    route: '/tools/regex-tester',
    color: 'red',
  },
  {
    id: 'api-tester',
    name: 'API Tester',
    category: 'developer',
    description: 'Test REST APIs with various HTTP methods',
    icon: 'fas fa-plug',
    route: '/tools/api-tester',
    color: 'blue',
  },
  {
    id: 'css-minifier',
    name: 'CSS Minifier',
    category: 'developer',
    description: 'Minify and optimize CSS code for production',
    icon: 'fab fa-css3-alt',
    route: '/tools/css-minifier',
    color: 'blue',
  },
  {
    id: 'html-validator',
    name: 'HTML Validator',
    category: 'developer',
    description: 'Validate HTML markup and find syntax errors',
    icon: 'fab fa-html5',
    route: '/tools/html-validator',
    color: 'orange',
  },
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    category: 'developer',
    description: 'Format and beautify SQL queries',
    icon: 'fas fa-database',
    route: '/tools/sql-formatter',
    color: 'gray',
  },
  {
    id: 'xml-formatter',
    name: 'XML Formatter',
    category: 'developer',
    description: 'Format and validate XML documents',
    icon: 'fas fa-code',
    route: '/tools/xml-formatter',
    color: 'green',
  },
  {
    id: 'markdown-editor',
    name: 'Markdown Editor',
    category: 'developer',
    description: 'Live markdown editor with preview',
    icon: 'fab fa-markdown',
    route: '/tools/markdown-editor',
    color: 'purple',
  },

  // Text Analysis & Processing
  {
    id: 'word-counter',
    name: 'Word Counter',
    category: 'text',
    description: 'Count words, characters, and analyze text statistics',
    icon: 'fas fa-font',
    route: '/tools/word-counter',
    color: 'yellow',
  },
  {
    id: 'text-encryptor',
    name: 'Text Encryptor',
    category: 'text',
    description: 'Encrypt and decrypt text using various algorithms',
    icon: 'fas fa-lock',
    route: '/tools/text-encryptor',
    color: 'red',
  },
  {
    id: 'text-to-speech',
    name: 'Text to Speech',
    category: 'text',
    description: 'Convert text to natural-sounding speech',
    icon: 'fas fa-volume-up',
    route: '/tools/text-to-speech',
    color: 'blue',
  },
  {
    id: 'language-translator',
    name: 'Language Translator',
    category: 'text',
    description: 'Translate text between multiple languages',
    icon: 'fas fa-language',
    route: '/tools/language-translator',
    color: 'green',
  },

  // Security Tools
  {
    id: 'password-generator',
    name: 'Password Generator',
    category: 'security',
    description: 'Generate secure passwords with customizable options',
    icon: 'fas fa-key',
    route: '/tools/password-generator',
    color: 'green',
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    category: 'security',
    description: 'Generate MD5, SHA1, SHA256 hashes for text',
    icon: 'fas fa-hashtag',
    route: '/tools/hash-generator',
    color: 'purple',
  },
  {
    id: 'ssl-checker',
    name: 'SSL Certificate Checker',
    category: 'security',
    description: 'Check SSL certificate validity and details',
    icon: 'fas fa-certificate',
    route: '/tools/ssl-checker',
    color: 'blue',
  },

  // Converters
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    category: 'converters',
    description: 'Convert between different units of measurement',
    icon: 'fas fa-exchange-alt',
    route: '/tools/unit-converter',
    color: 'orange',
  },
  {
    id: 'base64-converter',
    name: 'Base64 Converter',
    category: 'converters',
    description: 'Encode and decode Base64 strings',
    icon: 'fas fa-code',
    route: '/tools/base64-converter',
    color: 'gray',
  },
  {
    id: 'csv-to-json',
    name: 'CSV to JSON',
    category: 'converters',
    description: 'Convert CSV data to JSON format',
    icon: 'fas fa-table',
    route: '/tools/csv-to-json',
    color: 'green',
  },
  {
    id: 'color-converter',
    name: 'Color Converter',
    category: 'converters',
    description: 'Convert colors between HEX, RGB, HSL formats',
    icon: 'fas fa-palette',
    route: '/tools/color-converter',
    color: 'pink',
  },
  {
    id: 'timezone-converter',
    name: 'Timezone Converter',
    category: 'converters',
    description: 'Convert time between different timezones',
    icon: 'fas fa-globe',
    route: '/tools/timezone-converter',
    color: 'blue',
  },
  {
    id: 'pdf-converter',
    name: 'PDF Converter Suite',
    category: 'converters',
    description: 'Convert PDFs to Word, Excel, Images, Text and more. Merge, split, compress PDFs',
    icon: 'fas fa-file-pdf',
    route: '/tools/pdf-converter',
    color: 'red',
  },

  // Generators
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    category: 'generators',
    description: 'Generate QR codes for URLs, text, and contact info',
    icon: 'fas fa-qrcode',
    route: '/tools/qr-generator',
    color: 'gray',
  },
  {
    id: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    category: 'generators',
    description: 'Generate placeholder text for design and development',
    icon: 'fas fa-align-left',
    route: '/tools/lorem-ipsum-generator',
    color: 'purple',
  },
  {
    id: 'barcode-generator',
    name: 'Barcode Generator',
    category: 'generators',
    description: 'Generate various types of barcodes',
    icon: 'fas fa-barcode',
    route: '/tools/barcode-generator',
    color: 'gray',
  },
  {
    id: 'color-palette-generator',
    name: 'Color Palette Generator',
    category: 'generators',
    description: 'Generate beautiful color palettes for design',
    icon: 'fas fa-swatchbook',
    route: '/tools/color-palette-generator',
    color: 'pink',
  },
  {
    id: 'gradient-generator',
    name: 'Gradient Generator',
    category: 'generators',
    description: 'Create CSS gradients with live preview',
    icon: 'fas fa-fill-drip',
    route: '/tools/gradient-generator',
    color: 'purple',
  },
  {
    id: 'meta-tag-generator',
    name: 'Meta Tag Generator',
    category: 'generators',
    description: 'Generate SEO meta tags for websites',
    icon: 'fas fa-tags',
    route: '/tools/meta-tag-generator',
    color: 'blue',
  },
  {
    id: 'favicon-generator',
    name: 'Favicon Generator',
    category: 'generators',
    description: 'Generate favicons from images or text',
    icon: 'fas fa-star',
    route: '/tools/favicon-generator',
    color: 'orange',
  },

  // Calculators
  {
    id: 'bmi-calculator',
    name: 'BMI Calculator',
    category: 'calculators',
    description: 'Calculate Body Mass Index and health metrics',
    icon: 'fas fa-weight',
    route: '/tools/bmi-calculator',
    color: 'green',
  },
  {
    id: 'loan-calculator',
    name: 'Loan Calculator',
    category: 'calculators',
    description: 'Calculate loan payments and interest rates',
    icon: 'fas fa-percent',
    route: '/tools/loan-calculator',
    color: 'blue',
  },
  {
    id: 'age-calculator',
    name: 'Age Calculator',
    category: 'calculators',
    description: 'Calculate exact age in years, months, and days',
    icon: 'fas fa-birthday-cake',
    route: '/tools/age-calculator',
    color: 'pink',
  },
  {
    id: 'date-calculator',
    name: 'Date Calculator',
    category: 'calculators',
    description: 'Calculate differences between dates',
    icon: 'fas fa-calendar-alt',
    route: '/tools/date-calculator',
    color: 'purple',
  },
  {
    id: 'percentage-calculator',
    name: 'Percentage Calculator',
    category: 'calculators',
    description: 'Calculate percentages, increases, and decreases',
    icon: 'fas fa-percentage',
    route: '/tools/percentage-calculator',
    color: 'orange',
  },
  {
    id: 'tip-calculator',
    name: 'Tip Calculator',
    category: 'calculators',
    description: 'Calculate tips and split bills among friends',
    icon: 'fas fa-dollar-sign',
    route: '/tools/tip-calculator',
    color: 'green',
  },

  // Networking Tools
  {
    id: 'ip-lookup',
    name: 'IP Address Lookup',
    category: 'networking',
    description: 'Get detailed information about IP addresses',
    icon: 'fas fa-search-location',
    route: '/tools/ip-lookup',
    color: 'blue',
  },
  {
    id: 'domain-whois',
    name: 'Domain WHOIS Lookup',
    category: 'networking',
    description: 'Get domain registration and ownership details',
    icon: 'fas fa-search',
    route: '/tools/domain-whois',
    color: 'gray',
  },
  {
    id: 'port-scanner',
    name: 'Port Scanner',
    category: 'networking',
    description: 'Scan open ports on servers and websites',
    icon: 'fas fa-ethernet',
    route: '/tools/port-scanner',
    color: 'red',
  },
  {
    id: 'ping-test',
    name: 'Ping Test',
    category: 'networking',
    description: 'Test network connectivity and latency',
    icon: 'fas fa-wifi',
    route: '/tools/ping-test',
    color: 'green',
  },
  {
    id: 'speed-test',
    name: 'Network Speed Test',
    category: 'networking',
    description: 'Test internet download and upload speeds',
    icon: 'fas fa-tachometer-alt',
    route: '/tools/speed-test',
    color: 'blue',
  },

  // Productivity Tools
  {
    id: 'pomodoro-timer',
    name: 'Pomodoro Timer',
    category: 'productivity',
    description: 'Focus timer with customizable work and break intervals',
    icon: 'fas fa-clock',
    route: '/tools/pomodoro-timer',
    color: 'red',
  },
  {
    id: 'notes-app',
    name: 'Notes App',
    category: 'productivity',
    description: 'Create, edit, and organize your notes',
    icon: 'fas fa-sticky-note',
    route: '/tools/notes-app',
    color: 'yellow',
  },
  {
    id: 'todo-list',
    name: 'Todo List',
    category: 'productivity',
    description: 'Manage tasks and track your productivity',
    icon: 'fas fa-list-check',
    route: '/tools/todo-list',
    color: 'green',
  },
  {
    id: 'habit-tracker',
    name: 'Habit Tracker',
    category: 'productivity',
    description: 'Track daily habits and build routines',
    icon: 'fas fa-chart-line',
    route: '/tools/habit-tracker',
    color: 'purple',
  },
  {
    id: 'expense-tracker',
    name: 'Expense Tracker',
    category: 'productivity',
    description: 'Track and categorize your daily expenses',
    icon: 'fas fa-wallet',
    route: '/tools/expense-tracker',
    color: 'emerald',
  },

  // Utilities
  {
    id: 'email-validator',
    name: 'Email Validator',
    category: 'utilities',
    description: 'Validate email addresses and check syntax',
    icon: 'fas fa-envelope-open-text',
    route: '/tools/email-validator',
    color: 'blue',
  },
  {
    id: 'url-shortener',
    name: 'URL Shortener',
    category: 'utilities',
    description: 'Create short URLs and track click analytics',
    icon: 'fas fa-link',
    route: '/tools/url-shortener',
    color: 'green',
  },
  {
    id: 'website-screenshot',
    name: 'Website Screenshot',
    category: 'utilities',
    description: 'Capture full-page screenshots of any website',
    icon: 'fas fa-camera',
    route: '/tools/website-screenshot',
    color: 'blue',
  },
  {
    id: 'file-compressor',
    name: 'File Compressor',
    category: 'utilities',
    description: 'Compress files and folders to reduce size',
    icon: 'fas fa-file-archive',
    route: '/tools/file-compressor',
    color: 'orange',
  },
  {
    id: 'duplicate-finder',
    name: 'Duplicate File Finder',
    category: 'utilities',
    description: 'Find and remove duplicate files',
    icon: 'fas fa-copy',
    route: '/tools/duplicate-finder',
    color: 'red',
  },
  {
    id: 'weather-dashboard',
    name: 'Weather Dashboard',
    category: 'utilities',
    description: 'Get current weather and forecasts for any location',
    icon: 'fas fa-cloud-sun',
    route: '/tools/weather-dashboard',
    color: 'sky',
  },

  // Content Creation
  {
    id: 'meme-generator',
    name: 'Meme Generator',
    category: 'content',
    description: 'Create funny memes with custom text and images',
    icon: 'fas fa-laugh',
    route: '/tools/meme-generator',
    color: 'yellow',
  },
  {
    id: 'quote-generator',
    name: 'Quote Generator',
    category: 'content',
    description: 'Generate inspirational and random quotes',
    icon: 'fas fa-quote-left',
    route: '/tools/quote-generator',
    color: 'purple',
  },
  {
    id: 'social-media-generator',
    name: 'Social Media Post',
    category: 'content',
    description: 'Create engaging social media posts with templates',
    icon: 'fas fa-share-alt',
    route: '/tools/social-media-generator',
    color: 'pink',
  },
  {
    id: 'invoice-generator',
    name: 'Invoice Generator',
    category: 'content',
    description: 'Create professional invoices and receipts',
    icon: 'fas fa-file-invoice',
    route: '/tools/invoice-generator',
    color: 'blue',
  },
  {
    id: 'resume-builder',
    name: 'Resume Builder',
    category: 'content',
    description: 'Build professional resumes with templates',
    icon: 'fas fa-file-alt',
    route: '/tools/resume-builder',
    color: 'green',
  },

  // Financial Tools
  {
    id: 'budget-calculator',
    name: 'Budget Calculator',
    category: 'financial',
    description: 'Plan and track your monthly budget',
    icon: 'fas fa-chart-pie',
    route: '/tools/budget-calculator',
    color: 'green',
  },
  {
    id: 'investment-calculator',
    name: 'Investment Calculator',
    category: 'financial',
    description: 'Calculate returns on investments and savings',
    icon: 'fas fa-chart-line',
    route: '/tools/investment-calculator',
    color: 'blue',
  },
  {
    id: 'tax-calculator',
    name: 'Tax Calculator',
    category: 'financial',
    description: 'Calculate income tax and deductions',
    icon: 'fas fa-receipt',
    route: '/tools/tax-calculator',
    color: 'red',
  },
  {
    id: 'currency-converter',
    name: 'Currency Converter',
    category: 'financial',
    description: 'Convert between different currencies with live rates',
    icon: 'fas fa-coins',
    route: '/tools/currency-converter',
    color: 'yellow',
  },

  // AI & Automation
  {
    id: 'chatbot',
    name: 'AI Chatbot',
    category: 'ai',
    description: 'Chat with an AI assistant for help and answers',
    icon: 'fas fa-robot',
    route: '/tools/chatbot',
    color: 'blue',
  },
  {
    id: 'content-summarizer',
    name: 'Content Summarizer',
    category: 'ai',
    description: 'Automatically summarize long text content',
    icon: 'fas fa-compress',
    route: '/tools/content-summarizer',
    color: 'purple',
  },
  {
    id: 'keyword-extractor',
    name: 'Keyword Extractor',
    category: 'ai',
    description: 'Extract keywords and key phrases from text',
    icon: 'fas fa-key',
    route: '/tools/keyword-extractor',
    color: 'orange',
  },
  {
    id: 'sentiment-analyzer',
    name: 'Sentiment Analyzer',
    category: 'ai',
    description: 'Analyze text sentiment and emotions',
    icon: 'fas fa-smile',
    route: '/tools/sentiment-analyzer',
    color: 'green',
  },
];

export const getToolsByCategory = (category: string) => {
  if (category === 'all') return tools;
  return tools.filter(tool => tool.category === category);
};

export const searchTools = (query: string) => {
  const lowercaseQuery = query.toLowerCase();
  return tools.filter(tool => 
    tool.name.toLowerCase().includes(lowercaseQuery) ||
    tool.description.toLowerCase().includes(lowercaseQuery) ||
    tool.category.toLowerCase().includes(lowercaseQuery)
  );
};
